Pull Request for Hackathon
mayhemheroes/quicly pull request #1
Opened 2022-05-16 00:13 UTC by ennamarie19

2022-06-14 21:02 UTC, xansec requested changes
Please make the requested changes.

2022-06-14 21:02 UTC, xansec commented on Dockerfile
> +# Build Stage
You do not need to clone the source here - you can simply do `ADD . /quicly` (since the source is already checked out as part of the action). Also, we have changed the name corpus -> testsuite; could you please update it?

2022-06-14 21:02 UTC, xansec commented on fuzz/packet.cc
>  extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size)
Could you comment on why these changes were made?

2022-06-21 18:40 UTC, xansec commented on fuzz/packet.cc
>  extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size)
Still looking for comments on why the changes to `packet.cc` were made, can you help clarify?

2022-06-21 18:41 UTC, xansec commented
Is the testsuite generated by Mayhem? After more review, I don't believe you need to commit this - the testsuite will be maintained by Mayhem (unless there is a seed that is important to get started).

2022-06-21 19:16 UTC, ennamarie19 commented on fuzz/packet.cc
>  extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size)
Since whenever the fuzzer was written, they updated the function signature for quicly_decode_packet which causes it to now require a fifth parameter. I added that missing parameter in. Before this change, the fuzzer would crash.

Sorry, my original reply says "Pending", so I am guessing it did not go through!

2022-06-21 19:19 UTC, merged